/**
 * generate-registry.ts
 * Build-time script: scans ../../../src/components and writes a typed SourceCodeMap
 * to src/catalogue/registry.generated.ts.
 *
 * Run via: npm run generate
 * AUTO-GENERATED OUTPUT — do not edit registry.generated.ts by hand.
 */

import * as fs from 'fs';
import * as path from 'path';

const COMPONENTS_DIR = path.resolve(__dirname, '../../../src/components');
const OUTPUT_FILE = path.resolve(__dirname, '../src/catalogue/registry.generated.ts');

/**
 * For a given component directory, find the best source file to display:
 * 1. ComponentName.tsx  (primary implementation)
 * 2. index.ts / index.tsx  (barrel fallback)
 * Returns empty string if none found.
 */
function resolveSourceFile(componentDir: string, componentName: string): string {
  const candidates = [
    path.join(componentDir, `${componentName}.tsx`),
    path.join(componentDir, `${componentName}.ts`),
    path.join(componentDir, 'index.tsx'),
    path.join(componentDir, 'index.ts'),
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }
  return '';
}

function main(): void {
  if (!fs.existsSync(COMPONENTS_DIR)) {
    console.error(`Components directory not found: ${COMPONENTS_DIR}`);
    process.exit(1);
  }

  const entries = fs
    .readdirSync(COMPONENTS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * registry.generated.ts');
  lines.push(' * AUTO-GENERATED by scripts/generate-registry.ts — do not edit by hand.');
  lines.push(` * Generated: ${new Date().toISOString()}`);
  lines.push(' */');
  lines.push('');
  lines.push('export type SourceCodeMap = Record<string, string>;');
  lines.push('');
  lines.push('const sourceCodeMap: SourceCodeMap = {');

  let count = 0;
  for (const name of entries) {
    const componentDir = path.join(COMPONENTS_DIR, name);
    const sourceFile = resolveSourceFile(componentDir, name);
    let sourceCode = '';

    if (sourceFile) {
      try {
        sourceCode = fs.readFileSync(sourceFile, 'utf8');
      } catch {
        sourceCode = '';
      }
    }

    // Escape backticks and template literal delimiters for safe embedding
    const escaped = sourceCode
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$\{/g, '\\${');

    lines.push(`  ${JSON.stringify(name)}: \`${escaped}\`,`);
    count++;
  }

  lines.push('};');
  lines.push('');
  lines.push('export default sourceCodeMap;');
  lines.push('');

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf8');
  console.log(`✅ registry.generated.ts written — ${count} components indexed.`);
}

main();
