/**
 * MD3 Color Role tokens — static baseline values seeded from #1976D2.
 *
 * These 30 roles are the static fallback used when no runtime seedColor
 * is provided to createTheme(). The runtime values are generated by
 * generatePalette() in src/theme/generatePalette.ts.
 *
 * Reference: Material Design 3 Color System
 * https://m3.material.io/styles/color/roles
 */

export interface ColorScheme {
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  background: string;
  onBackground: string;
  surface: string;
  onSurface: string;
  surfaceVariant: string;
  onSurfaceVariant: string;
  outline: string;
  outlineVariant: string;
  shadow: string;
  scrim: string;
  inverseSurface: string;
  inverseOnSurface: string;
  inversePrimary: string;
  surfaceTint: string;
}

/** Default MD3 light color scheme seeded from #1976D2 */
export const baseLightColors: ColorScheme = {
  primary: '#1976D2',
  onPrimary: '#FFFFFF',
  primaryContainer: '#D1E4FF',
  onPrimaryContainer: '#001D35',
  secondary: '#535F70',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#D7E3F7',
  onSecondaryContainer: '#101C2B',
  tertiary: '#6B5778',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#F2DAFF',
  onTertiaryContainer: '#251431',
  error: '#B3261E',
  onError: '#FFFFFF',
  errorContainer: '#F9DEDC',
  onErrorContainer: '#410E0B',
  background: '#FDFBFF',
  onBackground: '#1A1C1E',
  surface: '#FDFBFF',
  onSurface: '#1A1C1E',
  surfaceVariant: '#DFE2EB',
  onSurfaceVariant: '#43474E',
  outline: '#73777F',
  outlineVariant: '#C3C7CF',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#2F3033',
  inverseOnSurface: '#F1F0F4',
  inversePrimary: '#A0C9FF',
  surfaceTint: '#1976D2',
};

/** Default MD3 dark color scheme seeded from #1976D2 */
export const baseDarkColors: ColorScheme = {
  primary: '#A0C9FF',
  onPrimary: '#003258',
  primaryContainer: '#004881',
  onPrimaryContainer: '#D1E4FF',
  secondary: '#BBC7DB',
  onSecondary: '#253140',
  secondaryContainer: '#3B4858',
  onSecondaryContainer: '#D7E3F7',
  tertiary: '#D6BEE4',
  onTertiary: '#3B2948',
  tertiaryContainer: '#523F5F',
  onTertiaryContainer: '#F2DAFF',
  error: '#F2B8B5',
  onError: '#601410',
  errorContainer: '#8C1D18',
  onErrorContainer: '#F9DEDC',
  background: '#1A1C1E',
  onBackground: '#E3E2E6',
  surface: '#1A1C1E',
  onSurface: '#E3E2E6',
  surfaceVariant: '#43474E',
  onSurfaceVariant: '#C3C7CF',
  outline: '#8D9199',
  outlineVariant: '#43474E',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#E3E2E6',
  inverseOnSurface: '#2F3033',
  inversePrimary: '#1976D2',
  surfaceTint: '#A0C9FF',
};
